// <auto-generated />
using System;
using UniversityLostFound.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace UniversityLostFound.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260917212739_LostAndFoundModel")]
    partial class LostAndFoundModel
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("UniversityLostFound.Domain.Announcements.Announcement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.ToTable("announcements", (string)null);
                });

            modelBuilder.Entity("UniversityLostFound.Domain.UniversityMembers.UniversityMember", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("UniversityId")
                        .IsRequired()
                        .HasMaxLength(9)
                        .HasColumnType("character varying(9)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTimeOffset?>("ValidFrom")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("ValidUntil")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("UniversityId")
                        .IsUnique();

                    b.ToTable("university_members", (string)null);
                });

            modelBuilder.Entity("UniversityLostFound.Domain.UniversityMembers.StaffAccount", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("UniversityMemberId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("UniversityMemberId")
                        .IsUnique();

                    b.ToTable("staff_accounts", (string)null);
                });

            modelBuilder.Entity("UniversityLostFound.Domain.Categories.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("categories", (string)null);
                });

            modelBuilder.Entity("UniversityLostFound.Domain.Categories.Question", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("questions", (string)null);
                });

            modelBuilder.Entity("UniversityLostFound.Domain.Categories.QuestionOption", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer");

                    b.Property<Guid>("QuestionId")
                        .HasColumnType("uuid");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.HasKey("Id");

                    b.HasIndex("QuestionId");

                    b.ToTable("question_options", (string)null);
                });

            modelBuilder.Entity("UniversityLostFound.Domain.Locations.UniversityLocation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("IsHandoverPoint")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("university_locations", (string)null);
                });

            modelBuilder.Entity("UniversityLostFound.Domain.Reports.Claim", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ClaimantUniversityMemberId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("DecidedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("DecidedByStaffId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("HandoverPointId")
                        .HasColumnType("uuid");

                    b.Property<DateOnly?>("LostOn")
                        .HasColumnType("date");

                    b.Property<Guid>("ReportId")
                        .HasColumnType("uuid");

                    b.Property<int>("Score")
                        .HasColumnType("integer");

                    b.Property<string>("SecretDescription")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("StaffNote")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("TrackingCode")
                        .IsRequired()
                        .HasMaxLength(9)
                        .HasColumnType("character varying(9)");

                    b.HasKey("Id");

                    b.HasIndex("ClaimantUniversityMemberId");

                    b.HasIndex("DecidedByStaffId");

                    b.HasIndex("HandoverPointId");

                    b.HasIndex("TrackingCode")
                        .IsUnique();

                    b.HasIndex("ReportId", "ClaimantUniversityMemberId")
                        .IsUnique();

                    b.HasIndex("Status", "Score");

                    b.ToTable("claims", (string)null);
                });

            modelBuilder.Entity("UniversityLostFound.Domain.Reports.ItemReport", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid");

                    b.Property<string>("CloseReason")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTimeOffset?>("ClosedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("HandoverConfirmedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("HandoverPointId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("LocationId")
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("OccurredOn")
                        .HasColumnType("date");

                    b.Property<string>("PublicDescription")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<Guid>("ReporterUniversityMemberId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("ReturnedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SecretDescription")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("TrackingCode")
                        .IsRequired()
                        .HasMaxLength(9)
                        .HasColumnType("character varying(9)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("HandoverPointId");

                    b.HasIndex("LocationId");

                    b.HasIndex("ReporterUniversityMemberId");

                    b.HasIndex("TrackingCode")
                        .IsUnique();

                    b.HasIndex("Type", "Status", "OccurredOn");

                    b.ToTable("item_reports", (string)null);
                });

            modelBuilder.Entity("UniversityLostFound.Domain.UniversityMembers.StaffAccount", b =>
                {
                    b.HasOne("UniversityLostFound.Domain.UniversityMembers.UniversityMember", null)
                        .WithOne()
                        .HasForeignKey("UniversityLostFound.Domain.UniversityMembers.StaffAccount", "UniversityMemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("UniversityLostFound.Domain.Categories.Question", b =>
                {
                    b.HasOne("UniversityLostFound.Domain.Categories.Category", null)
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("UniversityLostFound.Domain.Categories.QuestionOption", b =>
                {
                    b.HasOne("UniversityLostFound.Domain.Categories.Question", null)
                        .WithMany()
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("UniversityLostFound.Domain.Reports.Claim", b =>
                {
                    b.HasOne("UniversityLostFound.Domain.UniversityMembers.UniversityMember", null)
                        .WithMany()
                        .HasForeignKey("ClaimantUniversityMemberId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("UniversityLostFound.Domain.UniversityMembers.StaffAccount", null)
                        .WithMany()
                        .HasForeignKey("DecidedByStaffId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("UniversityLostFound.Domain.Locations.UniversityLocation", null)
                        .WithMany()
                        .HasForeignKey("HandoverPointId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("UniversityLostFound.Domain.Reports.ItemReport", null)
                        .WithMany("Claims")
                        .HasForeignKey("ReportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsMany("UniversityLostFound.Domain.Reports.SecretAnswer", "Answers", b1 =>
                        {
                            b1.Property<Guid>("ClaimId")
                                .HasColumnType("uuid");

                            b1.Property<Guid>("QuestionId")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid");

                            b1.Property<Guid>("OptionId")
                                .HasColumnType("uuid");

                            b1.HasKey("ClaimId", "QuestionId");

                            b1.ToTable("claim_secret_answers", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("ClaimId");
                        });

                    b.Navigation("Answers");
                });

            modelBuilder.Entity("UniversityLostFound.Domain.Reports.ItemReport", b =>
                {
                    b.HasOne("UniversityLostFound.Domain.Categories.Category", null)
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("UniversityLostFound.Domain.Locations.UniversityLocation", null)
                        .WithMany()
                        .HasForeignKey("HandoverPointId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("UniversityLostFound.Domain.Locations.UniversityLocation", null)
                        .WithMany()
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("UniversityLostFound.Domain.UniversityMembers.UniversityMember", null)
                        .WithMany()
                        .HasForeignKey("ReporterUniversityMemberId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsMany("UniversityLostFound.Domain.Reports.SecretAnswer", "SecretAnswers", b1 =>
                        {
                            b1.Property<Guid>("ItemReportId")
                                .HasColumnType("uuid");

                            b1.Property<Guid>("QuestionId")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid");

                            b1.Property<Guid>("OptionId")
                                .HasColumnType("uuid");

                            b1.HasKey("ItemReportId", "QuestionId");

                            b1.ToTable("item_report_secret_answers", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("ItemReportId");
                        });

                    b.Navigation("SecretAnswers");
                });

            modelBuilder.Entity("UniversityLostFound.Domain.Reports.ItemReport", b =>
                {
                    b.Navigation("Claims");
                });
#pragma warning restore 612, 618
        }
    }
}
